# Generated by Django 4.0 on 2024-02-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollmo',
            new_name='rollno',
        ),
    ]
